services:
  postgres:
    image: postgres:15-alpine
    container_name: finance_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: finance
      POSTGRES_PASSWORD: finance123
      POSTGRES_DB: finance_db
    ports:
      - "5432:5432"
    volumes:
      - finance_pg_data:/var/lib/postgresql/data

volumes:
  finance_pg_data:
